### ISSUE TITLE
No repo field for npm package.json

### ISSUE THREAD

**Issue by maksutovic** [angularjs-foundation/video-exercises#1]
Hi, 
Trying to start module 1 exercises, however I get a warning:

npm WARN package.json AngularJS-foundation-app@0.0.1 No Repository field

Then trying to run grunt, it hangs on "Running "watch:assets" (watch) task
Waiting..."

New to npm and grunt, any help would be greatly apreciated.

**Comment by ghost** [comment]
I am also having a similar issue. But the server is also failing. It's pretty frustrating that I cannot even access the source for these videos due to build scripts failing. Any help would be greatly appreciated, thanks in advance....

In Windows environment when I run .scripts/install.cmd I get the following...
- npm WARN package.json angularjs-foundation-video-exercises@0.0.0 No repository f
  ield.

---

THEN a bunch of these...

Downloaded M6 into hands-on-exercises\M6
998 File(s) copied
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
Downloaded M7 into hands-on-exercises\M7

Resolving dependencies
The system cannot find the path specified.

---

THEN if I try to run the server I get this...

module.js:340
    throw err;
          ^
Error: Cannot find module 'C:\workspaces\Sandbox\angular\video-exercises\scripts
\node_modules\http-server\bin\http-server'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by simpulton** [comment]
Gentlemen -- I apologize! Looking into this now.

**Comment by ghost** [comment]
Thank you... I'm fairly new to git and npm so bear with me. It might be an issue of PEBCAK too!

**Comment by simpulton** [comment]
We have reworked the scripts and updated the README with accurate instructions. I have just tested it on a Windows machine and everything appeared to be in order. Please give it another spin and let me know if you run into any problems.

**Comment by ghost** [comment]
Fixed!! 

That worked. Thanks for the quick response and fix, you rock!
